language: node_js
sudo: required
services:
  - mongodb
cache:
   directories:
     - node_modules
node_js:
  - 6
before_script:
  - npm install
  - sleep 3
  - npm run start
  - sleep 5
script:
  - npm test server database
